name: Release Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  release_web:
    name: Web Release
    runs-on: ubuntu-latest

    steps:        
        - uses: actions/checkout@v1
          with: 
            repository: pminkov/threadpool    
            submodules: true
            
        
        - name: Configure Make
          run: make 
